version: "3.9"

services:

  backend:
    image: telmed_backend
    build:
      context: ./backend/TelMedBackend
      dockerfile: Dockerfile
    container_name: backend_api
    ports:
      - "5000:5000"

  frontend:
    image: telmed_frontend
    build:
      context: ./frontend/Login
      dockerfile: Dockerfile
    container_name: frontend_vue
    ports:
      - "5173:5173"
    depends_on:
      - backend