// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelMedAPI.Data;

#nullable disable

namespace TelMedAPI.Migrations
{
    [DbContext(typeof(TelMedAPIContext))]
    [Migration("20260414175857_DUI_Optional")]
    partial class DUI_Optional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelMedAPI.Models.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCita"));

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTimeOffset>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("LinkReunion")
                        .HasColumnType("text")
                        .HasColumnName("link_reunion");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<string>("TipoConsulta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_consulta");

                    b.HasKey("IdCita");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PacienteId");

                    b.ToTable("cita");
                });

            modelBuilder.Entity("TelMedAPI.Models.Consulta", b =>
                {
                    b.Property<int>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consulta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConsulta"));

                    b.Property<int>("CitaId")
                        .HasColumnType("integer")
                        .HasColumnName("cita_id");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diagnostico");

                    b.Property<string>("Evolucion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evolucion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("MedicamentosJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("medicamentos_json");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sintomas");

                    b.Property<string>("Tratamiento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tratamiento");

                    b.HasKey("IdConsulta");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.ToTable("consulta");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DUI")
                        .HasColumnType("text");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TelMedAPI.Models.Cita", b =>
                {
                    b.HasOne("Usuario", "Doctor")
                        .WithMany("CitasComoDoctor")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Usuario", "Paciente")
                        .WithMany("CitasComoPaciente")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("TelMedAPI.Models.Consulta", b =>
                {
                    b.HasOne("TelMedAPI.Models.Cita", "Cita")
                        .WithOne("Consulta")
                        .HasForeignKey("TelMedAPI.Models.Consulta", "CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("TelMedAPI.Models.Cita", b =>
                {
                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("CitasComoDoctor");

                    b.Navigation("CitasComoPaciente");
                });
#pragma warning restore 612, 618
        }
    }
}
